server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall_tiny?characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: homestead
    password: secret
  flyway:
    locations: classpath:db/migration